<?php

namespace SocialMedia\Poster\Tests;

use Illuminate\Foundation\Testing\DatabaseMigrations;

class TestCase extends \PHPUnit\Framework\TestCase
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
